name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  check-lint:
    runs-on: ubuntu-18.04

    steps:
      - name: Run Linter
        run: npx eslint .
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
