name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Super-Linter
        run: make lint
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
