name: style-aribnb

on: push

jobs:
  check-style:
    name: Lint code base
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Npm install
        run: npm install
      - name: Run make lint
        run: make lint
