name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  check-lint:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/setup-node@v1
        name: 'Setup Node'
        with:
          node-version: '14.x'
      - name: Install packages
        run: npm install
      - name: Test make
        run: make install
      - name: Install make
        run: sudo apt install make
      - name: Checking ES-Lint
        run: make lint
